export const MODULE_CUSTOM_METADATA = 'MODULE_CUSTOM_METADATA';
export const ROUTE_ACTION_METADATA = 'ROUTE_ACTION_METADATA';
export const ROUTE_TYPE_METADATA = 'ROUTE_METADATA';
export const REQUEST_USER_KEY = 'USER';
